// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit by hand.
import { forwardRef, type Ref, type SVGProps } from 'react';

interface Props extends SVGProps<SVGSVGElement> {
  title?: string;
  titleId?: string;
}

const SvgIconSearch = ({ title, titleId, ...props }: Props, ref: Ref<SVGSVGElement>) => (
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    aria-labelledby={titleId}
    {...props}
  >
    {title ? <title id={titleId}>{title}</title> : null}
    <circle cx="11" cy="11" r="7" stroke="currentColor" strokeWidth={2} />
    <path d="m20 20-3.6-3.6" stroke="currentColor" strokeWidth={2} strokeLinecap="round" />
  </svg>
);

const ForwardRef = forwardRef(SvgIconSearch);
export default ForwardRef;
